version: '3.8'

services:
 mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'crsDB'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_TCP_PORT: 3306
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:     
    - db:/var/lib/mysql

volumes:
  db:
    driver: local